// Auto-generated by scripts/compute_hyperball_params.py for ML-DSA-44
// (base grid: 400 MC samples, 2x K margin; resharing enlargement: 8000 MC
// samples via --resharing-only, kappa x base radii, 2x K margin).
//
// Resharing: measured honest overshoots (v5 coset splitter, fixed point) are
// (2,2) 0.794, (2,3) 0.827, (2,4) 0.991, (3,5) 1.023, (4,6) 1.166 — nearly
// identical to ML-DSA-87. (2,4)/(3,5) ship kappa-enlarged radii and K below
// (kappa = 1.10 / 1.15). (4,6) CANNOT be enlarged on this parameter set: its
// tight verification ceilings (gamma1 = 2^17, gamma2 = (Q-1)/88) collapse the
// per-iteration acceptance at kappa = 1.25 (MC K ~ 5.8e5), so (4,6) keeps
// base signing parameters and resharing *into* a 4-of-6 committee fails
// closed at the Round-5 recovered-partial guard (overshoot 1.166 > kappa 1).
// Freshly-dealt/DKG 4-of-6 committees sign normally.

pub(super) const K_ITERATIONS: &[(u32, u32, u32)] = &[
	(2, 2, 4),
	(2, 3, 6),
	(3, 3, 10),
	(2, 4, 16),
	(3, 4, 20),
	(4, 4, 26),
	(2, 5, 10),
	(3, 5, 696),
	(4, 5, 162),
	(5, 5, 74),
	(2, 6, 10),
	(3, 6, 82),
	(4, 6, 584),
	(5, 6, 966),
	(6, 6, 204),
];

pub(super) const HYPERBALL: &[(u32, u32, f64, f64, f64)] = &[
	(2, 2, 164656.6, 164698.4, 6.0),
	(2, 3, 175209.0, 175268.3, 6.0),
	(3, 3, 148350.9, 148392.8, 6.0),
	(2, 4, 192729.9, 192795.1, 6.0),
	(3, 4, 150499.8, 150559.2, 6.0),
	(4, 4, 123891.5, 123933.4, 6.0),
	(2, 5, 172218.2, 172291.1, 6.0),
	(3, 5, 172420.8, 172518.1, 6.0),
	(4, 5, 133104.0, 133177.2, 6.0),
	(5, 5, 112773.0, 112815.0, 6.0),
	(2, 6, 172218.2, 172291.1, 6.0),
	(3, 6, 152706.2, 152800.9, 6.0),
	(4, 6, 140270.0, 140365.0, 6.0),
	(5, 6, 120426.2, 120499.6, 6.0),
	(6, 6, 114483.6, 114525.5, 6.0),
];

/// Resharing enlargement `(t, n, κ)` for ML-DSA-44. `(4, 6)` is intentionally
/// absent (κ = 1): enlargement is infeasible under this variant's verification
/// ceilings, so reshares into 4-of-6 fail closed (see header comment).
pub(super) const RESHARING_KAPPA: &[(u32, u32, f64)] = &[(2, 4, 1.10), (3, 5, 1.15)];
