// Auto-generated by scripts/compute_hyperball_params.py for ML-DSA-65
// (radii: full grid search at 2000 MC samples; K: re-estimated at the shipped
// radii with 8000 MC samples via --refine-shipped, 2x margin).
//
// Resharing: measured honest overshoots (v5 coset splitter, fixed point) are
// below 1 for every supported committee — (2,2) 0.620, (2,3) 0.672,
// (2,4) 0.869, (3,5) 0.809, (4,6) 0.917 — because η=4 keygen variance (20/3)
// dwarfs the η=2-tuned split noise. All configs reshare at κ = 1 (base
// signing parameters), so the base tables below are used as-is.

/// No enlarged configs: every committee reshares at κ = 1.
pub(super) const RESHARING_KAPPA: &[(u32, u32, f64)] = &[];

pub(super) const K_ITERATIONS: &[(u32, u32, u32)] = &[
	(2, 2, 6),
	(2, 3, 10),
	(3, 3, 18),
	(2, 4, 12),
	(3, 4, 40),
	(4, 4, 52),
	(2, 5, 16),
	(3, 5, 128),
	(4, 5, 432),
	(5, 5, 160),
	(2, 6, 16),
	(3, 6, 192),
	(4, 6, 1546),
	(5, 6, 2444),
	(6, 6, 538),
];

pub(super) const HYPERBALL: &[(u32, u32, f64, f64, f64)] = &[
	(2, 2, 529159.1, 529276.3, 6.0),
	(2, 3, 560822.1, 560987.7, 7.0),
	(3, 3, 475166.1, 475283.1, 7.0),
	(2, 4, 559722.0, 559887.3, 8.0),
	(3, 4, 519627.5, 519793.8, 6.0),
	(4, 4, 454072.6, 454189.9, 6.0),
	(2, 5, 550711.2, 550914.6, 7.0),
	(3, 5, 563613.5, 563849.4, 6.0),
	(4, 5, 501199.2, 501402.8, 7.0),
	(5, 5, 418504.7, 418622.2, 6.0),
	(2, 6, 549630.9, 549833.9, 8.0),
	(3, 6, 564634.4, 564898.5, 6.0),
	(4, 6, 530263.4, 530527.7, 6.0),
	(5, 6, 493841.9, 494046.2, 6.0),
	(6, 6, 414896.4, 415013.8, 6.0),
];
