// Auto-generated by scripts/compute_hyperball_params.py for ML-DSA-65
// (radii: full grid search at 2000 MC samples; K: re-estimated at the shipped
// radii with 8000 MC samples via --refine-shipped, 2x margin).
//
// Resharing: split-noise intensity is calibrated per committee
// (`split_noise_num_x256(S_old)`) so the fixed-point conditional variance of
// reshared shares is >= η = 4 keygen variance for every supported committee
// (measured 1.028–1.051 × keygen, `keyhiding_conditional.py --eta 4`) — the
// a-posteriori hiding argument holds at full keygen strength. Measured honest
// overshoots (v5 coset splitter, fixed point; fixed seed / worst of 6 seeds):
// (2,2) 0.774, (2,3) 0.789, (2,4) 0.973/0.980, (3,5) 0.934/0.961,
// (4,6) 1.124/1.131. κ follows the ML-DSA-87 margin policy: near-1 configs
// get κ = 1.10, the deep (4,6) gets κ = 1.18 (~4.1% over the worst seed —
// see the multi-seed test in resharing_tests.rs). Enlarged entries below
// carry κ-scaled radii; (4,6)'s K is pinned by a dedicated 400k-sample MC
// run at the enlarged radius. The resulting worst-case Round-2 frame is what
// sizes MAX_SIGNING_MESSAGE_SIZE.

/// Configs whose recovered-partial bound and hyperball radii are enlarged by
/// κ to accept honest post-resharing partials (per-committee split noise at
/// keygen-parity intensity; see file header).
pub(super) const RESHARING_KAPPA: &[(u32, u32, f64)] =
	&[(2, 4, 1.10), (3, 5, 1.10), (4, 6, 1.18)];

/// Every signing-supported `(t, n)` can also be reshared into on ML-DSA-65
/// (κ enlargements ship for all configs whose overshoot exceeds 1).
pub(super) const RESHARING_UNSUPPORTED: &[(u32, u32)] = &[];

pub(super) const K_ITERATIONS: &[(u32, u32, u32)] = &[
	(2, 2, 6),
	(2, 3, 10),
	(3, 3, 18),
	(2, 4, 14), // kappa-enlarged (1.10)
	(3, 4, 40),
	(4, 4, 52),
	(2, 5, 16),
	(3, 5, 208), // kappa-enlarged (1.10)
	(4, 5, 432),
	(5, 5, 160),
	(2, 6, 16),
	(3, 6, 192),
	(4, 6, 7560), // kappa-enlarged (1.18); K pinned at 400k MC samples

	(5, 6, 2444),
	(6, 6, 538),
];

pub(super) const HYPERBALL: &[(u32, u32, f64, f64, f64)] = &[
	(2, 2, 529159.1, 529276.3, 6.0),
	(2, 3, 560822.1, 560987.7, 7.0),
	(3, 3, 475166.1, 475283.1, 7.0),
	(2, 4, 615694.2, 615876.0, 8.0), // kappa-enlarged: base (559722.0, 559887.3) x 1.10
	(3, 4, 519627.5, 519793.8, 6.0),
	(4, 4, 454072.6, 454189.9, 6.0),
	(2, 5, 550711.2, 550914.6, 7.0),
	(3, 5, 619974.9, 620234.3, 6.0), // kappa-enlarged: base (563613.5, 563849.4) x 1.10
	(4, 5, 501199.2, 501402.8, 7.0),
	(5, 5, 418504.7, 418622.2, 6.0),
	(2, 6, 549630.9, 549833.9, 8.0),
	(3, 6, 564634.4, 564898.5, 6.0),
	(4, 6, 625710.8, 626022.7, 6.0), // kappa-enlarged: base (530263.4, 530527.7) x 1.18

	(5, 6, 493841.9, 494046.2, 6.0),
	(6, 6, 414896.4, 415013.8, 6.0),
];
