// Auto-generated by scripts/compute_hyperball_params.py for ML-DSA-44
// (radii: full grid search at 2000 MC samples; K: re-estimated at the shipped
// radii with 8000 MC samples via --refine-shipped, 2x margin; resharing
// enlargement: kappa x base radii, K at the enlarged radii, same 8000/2x).
//
// Resharing: measured honest overshoots (v5 coset splitter, fixed point) are
// (2,2) 0.794, (2,3) 0.827, (2,4) 0.991, (3,5) 1.023, (4,6) 1.166 — nearly
// identical to ML-DSA-87. (2,4)/(3,5) ship kappa-enlarged radii and K below
// (kappa = 1.10 / 1.15). (4,6) CANNOT be enlarged on this parameter set: its
// tight verification ceilings (gamma1 = 2^17, gamma2 = (Q-1)/88) collapse the
// per-iteration acceptance at kappa = 1.25, so (4,6) keeps base signing
// parameters and resharing *into* a 4-of-6 committee is unsupported: it is
// listed in RESHARING_UNSUPPORTED below and rejected when the resharing
// session is configured (it would otherwise fail closed at the Round-5
// recovered-partial guard, overshoot 1.166 > kappa 1, after all parties
// spent Rounds 1-5). Freshly-dealt/DKG 4-of-6 committees sign normally.

pub(super) const K_ITERATIONS: &[(u32, u32, u32)] = &[
	(2, 2, 6),
	(2, 3, 10),
	(3, 3, 16),
	(2, 4, 14),
	(3, 4, 38),
	(4, 4, 48),
	(2, 5, 14),
	(3, 5, 488),
	(4, 5, 494),
	(5, 5, 170),
	(2, 6, 14),
	(3, 6, 210),
	(4, 6, 2450),
	(5, 6, 4196),
	(6, 6, 684),
];

pub(super) const HYPERBALL: &[(u32, u32, f64, f64, f64)] = &[
	(2, 2, 206062.2, 206125.0, 5.0),
	(2, 3, 218932.3, 219021.2, 5.0),
	(3, 3, 185560.8, 185623.7, 5.0),
	(2, 4, 240825.5, 240923.3, 5.0),
	(3, 4, 187867.2, 187956.2, 5.0),
	(4, 4, 154808.5, 154871.4, 5.0),
	(2, 5, 214870.5, 214979.6, 5.0),
	(3, 5, 214592.9, 214738.1, 5.0),
	(4, 5, 165700.1, 165809.5, 5.0),
	(5, 5, 147486.4, 147549.4, 5.0),
	(2, 6, 214870.5, 214979.6, 5.0),
	(3, 6, 189871.9, 190013.3, 5.0),
	(4, 6, 174241.4, 174383.0, 5.0),
	(5, 6, 149764.6, 149874.1, 5.0),
	(6, 6, 137723.6, 137786.6, 5.0),
];

/// Resharing enlargement `(t, n, κ)` for ML-DSA-44. `(4, 6)` is intentionally
/// absent (κ = 1): enlargement is infeasible under this variant's verification
/// ceilings, so reshares into 4-of-6 fail closed (see header comment).
pub(super) const RESHARING_KAPPA: &[(u32, u32, f64)] = &[(2, 4, 1.10), (3, 5, 1.15)];

/// New-committee `(t, n)` shapes that resharing *into* cannot produce on
/// ML-DSA-44, even though they are valid for signing (present in
/// `K_ITERATIONS`). The measured honest overshoot exceeds the base κ = 1
/// guard and no enlargement ships (see `RESHARING_KAPPA`), so the Round-5
/// recovered-partial guard is guaranteed to reject honest reshares.
/// `ResharingConfig` rejects these at construction time instead of failing
/// late.
pub(super) const RESHARING_UNSUPPORTED: &[(u32, u32)] = &[(4, 6)];
